// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPcAe5TBwvfRpt82D5GR5RF0SDNw3a9kQ',
    appId: '1:910423729114:web:3ff061dc3d024bc1e8d6e3',
    messagingSenderId: '910423729114',
    projectId: 'flutterfirebase-e4206',
    authDomain: 'flutterfirebase-e4206.firebaseapp.com',
    storageBucket: 'flutterfirebase-e4206.firebasestorage.app',
    measurementId: 'G-ZPVSY62RY8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArmrGF7tdel8O9CyyZyn31CIpO5riIKnc',
    appId: '1:910423729114:android:5353055a03f50ec7e8d6e3',
    messagingSenderId: '910423729114',
    projectId: 'flutterfirebase-e4206',
    storageBucket: 'flutterfirebase-e4206.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQnQzAbATN5MS9-9tr_ZDMGpydejXJwBE',
    appId: '1:910423729114:ios:ec27a74d7e485be8e8d6e3',
    messagingSenderId: '910423729114',
    projectId: 'flutterfirebase-e4206',
    storageBucket: 'flutterfirebase-e4206.firebasestorage.app',
    iosBundleId: 'com.example.adopet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQnQzAbATN5MS9-9tr_ZDMGpydejXJwBE',
    appId: '1:910423729114:ios:ec27a74d7e485be8e8d6e3',
    messagingSenderId: '910423729114',
    projectId: 'flutterfirebase-e4206',
    storageBucket: 'flutterfirebase-e4206.firebasestorage.app',
    iosBundleId: 'com.example.adopet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPcAe5TBwvfRpt82D5GR5RF0SDNw3a9kQ',
    appId: '1:910423729114:web:258b1852332d16e5e8d6e3',
    messagingSenderId: '910423729114',
    projectId: 'flutterfirebase-e4206',
    authDomain: 'flutterfirebase-e4206.firebaseapp.com',
    storageBucket: 'flutterfirebase-e4206.firebasestorage.app',
    measurementId: 'G-73L6Z3KL3E',
  );
}
